[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 100
known_third_party = ["django", "rest_framework", "environs"]

[tool.ruff]
line-length = 100
extend-select = ["I"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
testpaths = ["tests"]
python_files = ["test_*.py"]
